### ISSUE TITLE
About performance of gradCAM++

### ISSUE THREAD

**Issue by Danie1Hayes** [hugokitano/Classification-and-Localization-of-Disease-with-Bounding-Boxes-from-Chest-X-Ray-Images#1]
Hi,thanks for your work,i wonder if you could provide a  localization accuracy of gradCAM++ based on this densenet?
Or maybe could you display some pictures with ROI heat map covered?
I've been working on the localization problem on chest x-ray recently , i'm curious about how well could this post-processing work could be.
There is a good solution [(https://github.com/jfhealthcare/Chexpert)](url) ,but it need the model to be trained from scratch.

**Comment by Danie1Hayes** [comment]
In addition, i've tested grad-CAM and grad-CAM++  on some X-ray images in chexpert dataset's baseline densenet121, **BUT** it seems not good.

**Comment by hugokitano** [comment]
Here's the accompanying paper I wrote for this project. 
[Uploading CS230Final.pdf…]()

**Comment by hugokitano** [comment]
[CS230Final.pdf](https://github.com/hugokitano/Classification-and-Localization-of-Disease-with-Bounding-Boxes-from-Chest-X-Ray-Images/files/5454205/CS230Final.pdf)

**Comment by Danie1Hayes** [comment]
> [CS230Final.pdf](https://github.com/hugokitano/Classification-and-Localization-of-Disease-with-Bounding-Boxes-from-Chest-X-Ray-Images/files/5454205/CS230Final.pdf)

Thanks a lot!
